### ISSUE TITLE
Complete rspecs for TriannonClient class

### ISSUE THREAD

**Issue by dazza-codes** [sul-dlss/triannon-client#1]
See #TODO items in
https://github.com/sul-dlss/triannon-client/blob/master/spec/lib/triannon-client/triannon-client_spec.rb

The methods are all in
https://github.com/sul-dlss/triannon-client/blob/master/lib/triannon-client/triannon-client.rb

**Comment by dazza-codes** [comment]
@ndushay assigned so we can track pair-programming on these triannon-client specs

**Comment by dazza-codes** [comment]
Almost complete after https://github.com/sul-dlss/triannon-client/commit/1913db50221e31cac036e9898473a9093f7066e8

Should review triannon content negotiation for the /annotations route.  Should review rspec best practices for an HTTP client, although current specs appear to be reasonable.

**Comment by dazza-codes** [comment]
Revised code and rspecs today, added coveralls at https://coveralls.io/r/sul-dlss/triannon-client

**Comment by dazza-codes** [comment]
Exercise all of the supported mime types for triannon, see https://github.com/sul-dlss/triannon/issues/20

**Comment by dazza-codes** [comment]
Updated specs provide coverage at about 94%.  A pending spec on /annotations depends on https://github.com/sul-dlss/triannon/issues/117 and related triannon issues.

**Comment by azaroth42** [comment]
connected to #3

**Comment by dazza-codes** [comment]
Closing this ticket - all the current specs have been revised and enhanced with everything currently up to date; additional specs will be added for specific features like /search specs.

**Comment by azaroth42** [comment]
Yay! :) Good work!

On Mon, May 4, 2015 at 4:24 PM, Darren L. Weber, Ph.D. <
notifications@github.com> wrote:

> Closing this ticket - all the current specs have been revised and enhanced
> with everything currently up to date; additional specs will be added for
> specific features like /search specs.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sul-dlss/triannon-client/issues/1#issuecomment-98883608
> .

## 

Rob Sanderson
Information Standards Advocate
Digital Library Systems and Services
Stanford, CA 94305
