### ISSUE TITLE
Add /search client code

### ISSUE THREAD

**Issue by dazza-codes** [sul-dlss/triannon-client#2]
Latest triannon provides a `/search` endpoint, which defaults to everything.  (This should be effectively the same as the /annotations endpoint.)

Check the specs for details on parameters.

**Comment by ndushay** [comment]
Search specs at http://bit.ly/1GF7Mow .   Not all arguments have been implemented yet. See sul-dlss/triannon#127 to see which ones are available.

**Comment by dazza-codes** [comment]
See also documented parameters at https://github.com/sul-dlss/triannon#get-a-list-of-annos

**Comment by dazza-codes** [comment]
We've decided to skip this work because we are not yet clear about the stake holders and whether they want to use this client.  For the moment, the client satisfies the use cases for the bulk loading of annotations into triannon, without interactions on the /search endpoint.
