### ISSUE TITLE
Test /annotations from Client

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/triannon-client#4]
connected to sul-dlss/triannon#117
connected to sul-dlss/triannon#153
connected to sul-dlss/triannon#154

**Comment by dazza-codes** [comment]
Initial pass at testing this was committed, see https://github.com/sul-dlss/triannon-client/commit/3e3b30c55e1b917fe6d5d67be441c8043085213b#diff-1f6714aeebb57bd0766c973b12417243

**Comment by dazza-codes** [comment]
Additional tests should address handling for various content types (all the supported types and at least one that is not supported).

**Comment by dazza-codes** [comment]
The /annotations is redirected to /search and, without any parameters, it returns all the annotations.  This is already tested and working in the client.  Further work will be on the /search endpoint.
